name: Hugging Face Deployment

# Trigger the workflow on push events to the 'deployment' branch
on:
  push:
    branches:
      - deployment

jobs:
  build-and-deploy:
    # Run the job on the latest Ubuntu runner
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the latest code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment with version 3.9
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    # Step 3: Install the required dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements_dev.txt

    # Step 4: Build the Docker image to Docker Hub
    - name: Build Docker image
      run: |
        docker build . -t jackyzzz076/selector-deployment:latest

    # Step 5: Push the Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker login -u jackyzzz076 -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push jackyzzz076/selector-deployment:latest

    # Step 6: Install Hugging Face CLI
    - name: Install Hugging Face CLI
      run: |
        pip install -U "huggingface_hub[cli]"

    # Step 7: Authenticate with Hugging Face
    - name: Authenticate with Hugging Face
      run: |
        huggingface-cli login --token ${{ secrets.HUGGING_FACE_TOKEN }}

    # Step 8: Push Docker image to Hugging Face Space
    - name: Push to Hugging Face Space
      run: |
        huggingface-cli upload ./Dockerfile --repo-type=space --repo-id=JackyZzZzZ/selector
