name: Build and Publish

on:
  push:
    tags:
      - 'v*.*.*' # Only run this workflow for tags matching vX.X.X

jobs:
  build:
    runs-on: ubuntu-latest # Default runner for the build process
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Use the latest version of the checkout action

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build wheels
      run: |
        python setup.py sdist bdist_wheel

    - name: Upload wheel files
      uses: actions/upload-artifact@v4 # Upload artifacts for later use
      with:
        name: wheel-${{ matrix.os }}-py${{ matrix.python-version }}
        path: dist/*.whl

    - name: Test upload to Test PyPI
      run: |
        pip install twine
        twine upload --repository-url https://test.pypi.org/legacy/ dist/*

  publish:
    needs: build # Ensure the build job completes before this job runs
    if: startsWith(github.ref, 'refs/tags/') # Run this job only for tag pushes
    runs-on: ubuntu-latest # Default runner for the publish process

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Use the latest version of the checkout action

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install Twine
      run: |
        python -m pip install --upgrade pip
        pip install twine

    - name: Publish to PyPI
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }} # Use the PyPI token from GitHub secrets
      run: |
        twine upload dist/*
